---
title: "ANEP BEA Stats Query"
author: "Ed Sherwood"
date: "January 24, 2019"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(tidycensus) #Need an api key from US Census Bureau.
#library(tigris)
library(bea.R) #Need an api key from US BEA.
library(viridis)
library(rgdal)
library(sf)
library(maptools)
library(rmapshaper)
library(gridExtra)
library(mapview)
library(leaflet)
#options(tigris_class = "sf")
options(tigris_use_cache = TRUE)
knitr::opts_chunk$set(echo = TRUE)
```

## Get some US Cenus data

Download US Census data and overlay NEP boundaries:

```{r US Census Data}
nep_sf <- st_read(dsn = "./data-raw", layer = "NEP_Boundaries10162018")
states <- c("AL", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA",
            "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD",
            "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ",
            "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC",
            "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY",
            "PR")

totalpop_sf <- get_acs(geography = "county", variables = c(Population = "B01003_001"), 
                         state = states, geometry = TRUE)
ustotalpop_sf <- st_transform(totalpop_sf, st_crs(nep_sf))

nep_pop_intersects <- st_intersects(nep_sf, ustotalpop_sf)

nep_sel_sf <- ustotalpop_sf[unlist(nep_pop_intersects),]

nep_pop <- st_join(nep_sf, nep_sel_sf)

#nep_pop_simp <- ms_simplify(nep_pop) #Currently crashing R

```

## Plot US Census data by NEP Project Areas

Plot US Census data that's restricted to the NEP boundaries:

```{r echo=TRUE Display Census Data as a Map}

pal <- colorNumeric(palette = "viridis", domain = nep_pop$estimate, n = 10)


nep_pop %>%
    st_transform(crs = "+init=epsg:4326") %>%
    leaflet(width = "100%") %>%
    addProviderTiles(provider = "CartoDB.Positron") %>%
    addPolygons(popup = ~ str_extract(NAME, "^([^,]*)"),
                stroke = FALSE,
                smoothFactor = 0,
                fillOpacity = 0.7,
                color = ~ pal(estimate)) %>%
    addLegend("bottomright", 
              pal = pal, 
              values = ~ estimate,
              title = "Population",
              opacity = 1)

nep_pop %>%
#  mutate(pct = 100 * (value / summary_value)) %>%
  ggplot(aes(fill = estimate, color = pal())) +
  facet_wrap(~NEP_SHORT) +
  geom_sf() +
  scale_fill_viridis() +
  scale_color_viridis()

```

## Develop US BEA Plots

Work in progress ...  

```{r bea, echo=TRUE}

```
